### ISSUE TITLE
[ Javascipt ] Example part I

### ISSUE THREAD

**Issue by minhng271** [GraphicDThanh/minh-nguyen-internship#38]
- [x] Syntax
- [x] Semicolons
- [x] Values
- [x] Variables
- [x] Types
- [x] Expressions
- [x] Operators
- [x] Precedence
- [x] Comparisons
- [x] Conditionals
- [x] Strings
- [x] Arrays
- [x] Loops
- [x] Functions
- [x] Arrow Functions
- [x] Objects
- [x] Object properties
- [x] Object methods
- [x] Classes
- [x] Inheritance

**Comment by thanhnguyen-agilityio** [comment]
Please help create PR for this issue and send to supporter for review, thanks!
